server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    username: abmola
    password: "yasser1234"
    url: jdbc:mariadb://localhost:3306/ATELIER5?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
        format_sql: true
    show-sql: true
